BugSquish/BugSquish/Controllers/TicketCommentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BugSquish.Models;

namespace BugSquish.Controllers
{
    public class TicketCommentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: TicketComments
        public ActionResult Index()
        {
            var ticketComments = db.TicketComments.Include(t => t.Author).Include(t => t.Ticket);
            return View(ticketComments.ToList());
        }

        // GET: TicketComments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TicketComment ticketComment = db.TicketComments.Find(id);
            if (ticketComment == null)
            {
                return HttpNotFound();
            }
            return View(ticketComment);
        }

        // GET: TicketComments/Create
        [Authorize]
        public ActionResult Create(int id)
        {
            var user = db.Users.FirstOrDefault(u => u.UserName == User.Identity.Name).Id;
            
            var comment = new TicketComment
            {
                AuthorId = user,
                TicketId = id
                
            };
            return View(comment);
        }

        // POST: TicketComments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,AuthorId,TicketId,Created,Body")] TicketComment ticketComment)
        {
            if (ModelState.IsValid)
            {
                ticketComment.Created = new DateTimeOffset(DateTime.Now);
                db.TicketComments.Add(ticketComment);
                db.SaveChanges();
                return RedirectToAction("Details", "Tickets", new { id = ticketComment.TicketId});
            }

            return View(ticketComment);
        }

        //// GET: TicketComments/Edit/5
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    TicketComment ticketComment = db.TicketComments.Find(id);
        //    if (ticketComment == null)
        //    {
        //        return HttpNotFound();
        //    }

        //    return View(ticketComment);
        //}

        //// POST: TicketComments/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "Id,AuthorId,TicketId,Created,Body")] TicketComment ticketComment)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(ticketComment).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    ViewBag.AuthorId = new SelectList(db.Users, "Id", "FirstName", ticketComment.AuthorId);
        //    ViewBag.TicketId = new SelectList(db.Tickets, "Id", "AuthorId", ticketComment.TicketId);
        //    return View(ticketComment);
        //}

        // GET: TicketComments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TicketComment ticketComment = db.TicketComments.Find(id);
            if (ticketComment == null)
            {
                return HttpNotFound();
            }
            return View(ticketComment);
        }

        // POST: TicketComments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TicketComment ticketComment = db.TicketComments.Find(id);
            db.TicketComments.Remove(ticketComment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BugSquish/BugSquish/Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BugSquish.Models;
using Microsoft.AspNet.Identity;

namespace BugSquish.Controllers
{
    public class TicketsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        
        // GET: Tickets
        [Authorize]
        public ActionResult Index()
        {
            var user = db.Users.FirstOrDefault(u => u.UserName == User.Identity.Name);

            if (User.IsInRole("Admin"))
            {
                var tickets = db.Tickets.ToList();
                return View(tickets);
            }
            
            if (User.IsInRole("ProjectManager"))
            {
                var projects = db.Projects.Where(p => p.ManagerId == user.Id);

                
                var tickets = db.Tickets.Include(t => t.Author).Include(t => t.Developer).Include(t => t.Priority).Include(t => t.Project).Include(t => t.Status).Include(t => t.TicketType).Where(p => p.ProjectManagerId == user.Id).OrderByDescending(i => i.Created).ToList();
                return View(tickets);
            }
            
            if (User.IsInRole("Developer"))
            {
                var tickets = db.Tickets.Where(t => t.DeveloperId == user.Id).ToList();
                return View(tickets);
            }

            if (User.IsInRole("Submitter"))
            {
                var tickets = db.Tickets.Where(t => t.AuthorId == user.Id).OrderByDescending(i => i.Created).ToList();
                return View(tickets);
            }

            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        // GET: Tickets/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ticket ticket = db.Tickets.Find(id);
            if (ticket == null)
            {
                return HttpNotFound();
            }

            return View(ticket);
        }

        // GET: Tickets/Create
        public ActionResult Create()
        {
            var helper = new UserRolesHelper(db);
            var user = db.Users.FirstOrDefault(u => u.UserName == User.Identity.Name).Id;
            


            //ViewBag.AuthorId = new SelectList(db.Users, "Id", "FirstName");
            //ViewBag.DeveloperId = new SelectList(db.Users, "Id", "FirstName");
            //ViewBag.PriorityId = new SelectList(db.Priorities, "Id", "Name");
            //ViewBag.ProjectId = new SelectList(db.Projects, "Id", "ManagerId");
            //ViewBag.StatusId = new SelectList(db.Statuses, "Id", "Name");
            ViewBag.TicketTypeId = new SelectList(db.TicketTypes, "Id", "Name");
            ViewBag.ProjectId = new SelectList(db.Projects, "Id", "Name");

            var model = new Ticket
            {
                AuthorId = user
            };
                //ProjectManagerId = project.ManagerId,
                //ProjectManager = project.Manager};

            return View(model);
        }

        // POST: Tickets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,AuthorId,ProjectId,TicketTypeId,ProjectManagerId,PriorityId,StatusId,Title,Notes,Created")] Ticket ticket)
        {
            if (ModelState.IsValid)
            {
                //sets default user
                var user = db.Users.FirstOrDefault(u => u.UserName == User.Identity.Name);
                //finds the project in the database, used to then get project manager for ticket
                var manager = db.Projects.Single(p => p.Id == ticket.ProjectId).ManagerId;

                //assigns default status and priority to the ticket
                var status = db.Statuses.Single(s => s.Name == "Needs Review");


                //assigns manager to ticket
                ticket.ProjectManagerId = manager;
                //sets properties
                ticket.Created = new DateTimeOffset(DateTime.Now);
                ticket.StatusId = status.Id;


 
                ticket.AuthorId = user.Id;
                
                
                db.Tickets.Add(ticket);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AuthorId = new SelectList(db.Users, "Id", "FirstName", ticket.AuthorId);
            ViewBag.DeveloperId = new SelectList(db.Users, "Id", "FirstName", ticket.DeveloperId);
            ViewBag.PriorityId = new SelectList(db.Priorities, "Id", "Name", ticket.PriorityId);
            ViewBag.ProjectId = new SelectList(db.Projects, "Id", "ManagerId", ticket.ProjectId);
            ViewBag.StatusId = new SelectList(db.Statuses, "Id", "Name", ticket.StatusId);
            ViewBag.TicketTypeId = new SelectList(db.TicketTypes, "Id", "Name", ticket.TicketTypeId);
            return View(ticket);
        }

        // GET: Tickets/Edit/5
        [Authorize(Roles="Admin,ProjectManager,Developer")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ticket ticket = db.Tickets.Find(id);
            if (ticket == null)
            {
                return HttpNotFound();
            }


            ViewBag.DeveloperId = new SelectList(db.Users, "Id", "FirstName", ticket.DeveloperId);
            ViewBag.PriorityId = new SelectList(db.Priorities, "Id", "Name", ticket.PriorityId);
            ViewBag.StatusId = new SelectList(db.Statuses, "Id", "Name", ticket.StatusId);
            ViewBag.TicketTypeId = new SelectList(db.TicketTypes, "Id", "Name", ticket.TicketTypeId);
            return View(ticket);
        }
        
        // POST: Tickets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin,ProjectManager,Developer")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,AuthorId,ProjectId,DeveloperID,TicketTypeId,ProjectManagerId,PriorityId,StatusId,Title,Notes,Created,Updated")]Ticket ticket)
        {
            if (ModelState.IsValid)
            {
                var properties = new List<string>() {"Updated", "Description", "TicketTypeId", "TicketStatusId"};

                //gets ticket id and holds it for comparison
                var oldTicket = db.Tickets.AsNoTracking().FirstOrDefault(t => t.Id == ticket.Id);

                var user = db.Users.FirstOrDefault(u => u.UserName == User.Identity.Name).Id;


                if (User.IsInRole("Admin") || User.IsInRole("ProjectManager"))
                {
                    //Check Ticket Priority
                    if (oldTicket.PriorityId != ticket.PriorityId)
                    {
                        var newUser = db.Users.Find(ticket.DeveloperId);
                        properties.Add("TicketPriorityId");
                        var ChangedPriority = new TicketChange{
                            TicketId = ticket.Id,
                            EditorId = user,
                            Property = "Ticket Priority",
                            OldValue = db.Priorities.FirstOrDefault(p => p.Id == oldTicket.PriorityId).Name,
                            NewValue = db.Priorities.FirstOrDefault(p => p.Id == ticket.PriorityId).Name,
                            EditedTime = System.DateTimeOffset.Now
                        };

                        db.TicketChanges.Add(ChangedPriority);

                        if(newUser != null{
                            var mailer = new EmailService();
                            var Notification = newUser != null ? new IdentityMessage(){
                                Subject= "You have a new Notification",
                                Destination = newUser.Email,
                                Body = "The priority for your ticket: " + ticket.Title + " has been changed.\n" + Environment.NewLine + " The new priority is: " + db.Priorities.FirstOrDefault(p => p.Id == ticket.PriorityId).Name } : null;
                                mailer.Send(Notification);
                        }
                    }
                }
                ticket.Updated = new DateTimeOffset(DateTime.Now);
                db.Entry(ticket).State = EntityState.Modified;
                //DbExtensions.Update(db,["Title","Notes"]);

                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AuthorId = new SelectList(db.Users, "Id", "FirstName", ticket.AuthorId);
            ViewBag.DeveloperId = new SelectList(db.Users, "Id", "FirstName", ticket.DeveloperId);
            ViewBag.PriorityId = new SelectList(db.Priorities, "Id", "Name", ticket.PriorityId);
            ViewBag.ProjectId = new SelectList(db.Projects, "Id", "ManagerId", ticket.ProjectId);
            ViewBag.StatusId = new SelectList(db.Statuses, "Id", "Name", ticket.StatusId);
            ViewBag.TicketTypeId = new SelectList(db.TicketTypes, "Id", "Name", ticket.TicketTypeId);
            return View(ticket);
        }

        //GET: Tickets/Manage/5
        [Authorize(Roles = "Admin,ProjectManager")]
        public ActionResult Manage(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ticket ticket = db.Tickets.Find(id);

BugSquish/BugSquish/Views/Tickets/Create.cshtml
@model BugSquish.Models.Ticket

@{
    ViewBag.Title = "Create";
}


<div class="row">
    <div class="row">
        <div class="col-md-offset-1 col-md-6">
            <h2>New Ticket</h2>
            <hr />
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.AuthorId)

                    <div class="form-group">
                        @Html.LabelFor(model => model.ProjectId, "ProjectId", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("ProjectId", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.ProjectId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.TicketTypeId, "TicketTypeId", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("TicketTypeId", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.TicketTypeId, "", new { @class = "text-danger" })
                        </div>
                    </div>



                    <div class="form-group">
                        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Notes, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Notes, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger" })
                        </div>
                    </div>



                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-primary" />
                            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-info" })
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

BugSquish/BugSquish/Views/Tickets/Delete.cshtml
@model BugSquish.Models.Ticket

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Ticket</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Author.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Developer.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Developer.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Priority.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Priority.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Project.ManagerId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Project.ManagerId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TicketType.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TicketType.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Notes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Updated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Updated)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BugSquish/BugSquish/Views/Tickets/Details.cshtml
@model BugSquish.Models.Ticket

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>
<div class="row">
    <div class="row">
        <div class="col-md-offset-1 col-md-5">
            <!--attachments display panel-->
            <div class="panel panel-primary">
                <div class="panel-heading row">
                    <h4 class="col-md-4">
                        Attachments
                    </h4>
                    <div class="col-md-7 text-center">
                        @Html.ActionLink("Create New", "Create", "TicketAttachments", new { id = Model.Id }, new { @class = "btn btn-success pull-right" })
                    </div>
                </div>
                <table class="table">
                    <thead>
                        <tr>
                            <th>
                                Author
                            </th>
                            <th>
                                Notes
                            </th>
                            <th>
                                Created
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Attachments)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Author.FirstName) @Html.DisplayFor(modelItem => item.Author.LastName)
                                </td>
                                <td id=@("abstract" + item.Id)>
                                    @Html.DisplayFor(modelItem => item.Notes)
                                </td>
                                <td>
                                    @item.Created.ToString("D"))
                                </td>
                                <td>
                                    @Html.ActionLink("Details", "Details", "TicketAttachments", new { id = item.Id }, new { @class = "btn btn-xs btn-default" })
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>

            <div class="list-group">
            <hr />
                <div class="list-group-item">
                    <h5 class="list-group-item-heading">@Html.DisplayNameFor(model => model.Title)</h5>
                    <p class="list-group-item-text">@Html.DisplayFor(model => model.Title)</p>
                </div>

                <div class="list-group-item">
                    <h5 class="list-group-item-heading">@Html.DisplayNameFor(model => model.Author.FirstName)</h5>
                    <p class="list-group-item-text">@Html.DisplayFor(model => model.Author.FirstName) @Html.DisplayFor(model => model.Author.LastName)</p>
                </div>

                <div class="list-group-item">
                    <h5 class="list-group-item-heading">@Html.DisplayNameFor(model => model.Notes)</h5>
                    <p class="list-group-item-text">@Html.DisplayFor(model => model.Notes)</p>
                </div>

                <div class="list-group-item">
                    <div class="row">
                        <div class="col-md-6">
                            <h5 class="list-group-item-heading">@Html.DisplayNameFor(model => model.Created)</h5>
                            <p class="list-group-item-text">@Model.Created.ToString("d"))</p>
                        </div>
                        @if (Model.Updated.HasValue)
                        {
                        <div class="col-md-6">
                            <h5 class="list-group-item-heading">@Html.DisplayNameFor(model => model.Updated)</h5>
                            <p class="list-group-item-text">@Model.Updated.Value.ToString("d"))</p>
                        </div>
                        }
                    </div>

                </div>

                <div class="list-group-item">
                    <p class="list-group-item-text">
                        @if (User.IsInRole("Admin") || User.IsInRole("ProjectManager") || User.IsInRole("Developer"))
                        {
                            @Html.ActionLink("Edit Ticket", "Edit", new { id = Model.Id }, new { @class = "btn btn-primary" })
                        }
                        @Html.ActionLink("Back to Tickets Index", "Index", null, new { @class = "btn btn-info" })
                    </p>
                </div>
                <hr />
            </div> <!-- /.list-group -->



        </div>
        <div class="col-md-5">
            <!--comments display panel-->
            <div class="panel panel-primary">
                <div class="panel-heading row">
                    <h4 class="col-md-4">
                        Comments
                    </h4>
                    <div class="col-md-7 text-center">
                        @Html.ActionLink("Create New", "Create", "TicketComments", new { id = Model.Id }, new { @class = "btn btn-success pull-right" })
                    </div>
                </div>
                <table class="table">
                    <thead>
                        <tr>
                            <th>
                                Author
                            </th>
                            <th>
                                Body
                            </th>
                            <th>
                                Created
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Comments)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Author.FirstName) @Html.DisplayFor(modelItem => item.Author.LastName)
                                </td>
                                <td id=@("abstract" + item.Id)>
                                    @Html.DisplayFor(modelItem => item.Body)
                                </td>
                                <td>
                                    @item.Created.ToString("D"))
                                </td>
                                <td>
                                    @Html.ActionLink("Details", "Details", "TicketComments", new { id = item.Id }, new { @class = "btn btn-xs btn-default" })
                                    @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-xs btn-danger" })
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>

            <div class="list-group">
            <hr />
                <div class="list-group-item">
                    <h5 class="list-group-item-heading">@Html.DisplayNameFor(model => model.TicketType)</h5>
                    <p class="list-group-item-text">@Html.DisplayFor(model => model.TicketType.Name)</p>
                </div>

                <div class="list-group-item">
                    <h5 class="list-group-item-heading">@Html.DisplayNameFor(model => model.Priority)</h5>
                    <p class="list-group-item-text">@Html.DisplayFor(model => model.Priority.Name)</p>
                </div>    

                <div class="list-group-item">
                    <h5 class="list-group-item-heading">@Html.DisplayNameFor(model => model.Developer)</h5>
                    <p class="list-group-item-text">@Html.DisplayFor(model => model.Developer.FirstName) @Html.DisplayFor(model => model.Developer.LastName)</p>
                </div>

                <div class="list-group-item">
                    <h5 class="list-group-item-heading">@Html.DisplayNameFor(model => model.Status)</h5>
                    <p class="list-group-item-text">@Html.DisplayFor(model => model.Status.Name)</p>
                </div>
                        
                <div class="list-group-item">
                    <h5 class="list-group-item-heading">@Html.DisplayNameFor(model => model.Project.Manager)</h5>
                    <p class="list-group-item-text">@Html.DisplayFor(model => model.Project.Manager.FirstName) @Html.DisplayFor(model => model.Project.Manager.LastName)</p>
                </div>
            <hr />
            </div> <!-- /.list-group -->




        </div>
    </div>
</div>